POST http://localhost:8080/orders
Content-Type: application/json

{
  "userId": "HongGilDong",
  "productName": "MacBook Pro",
  "amount": 1,
  "totalPrice": 2309278,
  "address": "서울시 강동구 천호동"
}

###
