spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mysql://moko.dev:13306/kosta86?serverTimezon=Asia/Seoul&allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
    username: root
    password: kosta
  jpa:
    hibernate:
      ddl-auto: create

server:
  port: 8080